------------------------------------------------
-- HOTEL BOOKING DATABASE SCHEMA
------------------------------------------------

CREATE TABLE guests (
    guest_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    email VARCHAR2(100),
    address VARCHAR2(200),
    phone_number VARCHAR2(20),
    id_number VARCHAR2(20) UNIQUE
);

CREATE TABLE rooms (
    room_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR2(10),
    room_type VARCHAR2(50),
    price_per_night NUMBER
);

CREATE TABLE amenities (
    amenity_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amenity_name VARCHAR2(100),
    description VARCHAR2(200)
);

CREATE TABLE room_amenities (
    room_id NUMBER,
    amenity_id NUMBER,
    PRIMARY KEY (room_id, amenity_id),
    FOREIGN KEY (room_id) REFERENCES rooms(room_id),
    FOREIGN KEY (amenity_id) REFERENCES amenities(amenity_id)
);

CREATE TABLE reservations (
    reservation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id NUMBER,
    check_in_date DATE,
    check_out_date DATE,
    total_amount NUMBER,
    reservation_status VARCHAR2(20),
    FOREIGN KEY (guest_id) REFERENCES guests(guest_id)
);

CREATE TABLE reservation_rooms (
    reservation_id NUMBER,
    room_id NUMBER,
    number_of_nights NUMBER,
    PRIMARY KEY (reservation_id, room_id),
    FOREIGN KEY (reservation_id) REFERENCES reservations(reservation_id),
    FOREIGN KEY (room_id) REFERENCES rooms(room_id)
);

CREATE TABLE services (
    service_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR2(100),
    price NUMBER
);

CREATE TABLE reservation_services (
    reservation_id NUMBER,
    service_id NUMBER,
    quantity NUMBER,
    PRIMARY KEY (reservation_id, service_id),
    FOREIGN KEY (reservation_id) REFERENCES reservations(reservation_id),
    FOREIGN KEY (service_id) REFERENCES services(service_id)
);

CREATE TABLE ratings (
    rating_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id NUMBER,
    room_id NUMBER,
    score NUMBER,
    comment VARCHAR2(200),
    FOREIGN KEY (guest_id) REFERENCES guests(guest_id),
    FOREIGN KEY (room_id) REFERENCES rooms(room_id)
);

CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id NUMBER,
    payment_date DATE,
    amount NUMBER,
    payment_method VARCHAR2(50),
    FOREIGN KEY (reservation_id) REFERENCES reservations(reservation_id)
);